"""updated tables

Revision ID: b3d4c299c74c
Revises: 
Create Date: 2024-02-19 16:26:04.420276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d4c299c74c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork_classification')
    op.drop_table('classifications')
    op.drop_table('artwork_classifications')
    op.drop_table('classification')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_title', sa.Text(), nullable=False))
        batch_op.drop_column('id')
        batch_op.drop_column('name_title')

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_title', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('medium_display', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('style_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint('artworks_artist_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('artworks_classification_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artists', ['artist_title'], ['artist_title'])
        batch_op.create_foreign_key(None, 'styles', ['style_title'], ['name'])
        batch_op.drop_column('edu_material')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('classification_id')

    with op.batch_alter_table('centuries', schema=None) as batch_op:
        batch_op.alter_column('century_name',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_title', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_artist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artists', ['artist_title'], ['artist_title'])
        batch_op.drop_column('artist_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('century_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('century_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_artist_id_fkey', 'artists', ['artist_id'], ['id'])
        batch_op.drop_column('artist_title')

    with op.batch_alter_table('centuries', schema=None) as batch_op:
        batch_op.alter_column('century_name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('edu_material', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('artworks_classification_id_fkey', 'classification', ['classification_id'], ['name'])
        batch_op.create_foreign_key('artworks_artist_id_fkey', 'artists', ['artist_id'], ['id'])
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('style_title')
        batch_op.drop_column('medium_display')
        batch_op.drop_column('artist_title')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('artists_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('artist_title')

    op.create_table('classification',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='classification_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('artwork_classifications',
    sa.Column('artwork_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('classification_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], name='artwork_classifications_artwork_id_fkey'),
    sa.ForeignKeyConstraint(['classification_name'], ['classifications.name'], name='artwork_classifications_classification_name_fkey'),
    sa.PrimaryKeyConstraint('artwork_id', 'classification_name', name='artwork_classifications_pkey')
    )
    op.create_table('classifications',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='classifications_pkey')
    )
    op.create_table('artwork_classification',
    sa.Column('artwork_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('classification_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], name='artwork_classification_artwork_id_fkey'),
    sa.ForeignKeyConstraint(['classification_name'], ['classification.name'], name='artwork_classification_classification_name_fkey'),
    sa.PrimaryKeyConstraint('artwork_id', 'classification_name', name='artwork_classification_pkey')
    )
    # ### end Alembic commands ###
